apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "python.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "python.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else -}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.ENV }}
          env:
            {{- range $key, $val := .Values.ENV }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{ end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.dockerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.secrets }}
          volumeMounts:
            - name: kv-secrets
              mountPath: "/mnt/kvsecrets"
              readOnly: true
            {{- if .Values.storage.enable }}
            - name: pv-storage-mount
              mountPath: {{ .Values.storage.mountPath }}
            {{- end }}
          {{- end }}
      {{- if .Values.secrets }}
      volumes:      
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-{{ include "python.fullname" . }}
            nodePublishSecretRef:
              name: {{ .Values.keyvault.credentials }}
        {{- if .Values.storage.enable }}  
        - name: pv-storage-mount
          persistentVolumeClaim:
            claimName: {{ .Values.storage.provisionedPVC }}
        {{- end }}     
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
