apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-secrets-{{ include "python.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"               # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "false"         # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: ""            # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: {{ .Values.keyvault.name }}               # the name of the KeyVault
    cloudName: ""                         # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    cloudEnvFileName: ""                  # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects: |
      array:
        {{ range $item := .Values.secrets}}
          - |
            objectName: {{ . | quote }}
            objectAlias: ""
            objectType: secret
            objectVersion: ""
        {{ end }}
    tenantId: {{ .Values.keyvault.tenantId }}                       # the tenant ID of the KeyVault
    resourceGroup: {{ .Values.keyvault.resourceGroup }}
    subscriptionId: {{ .Values.keyvault.subscriptionId }}
