experiment_name: v3

sections:
  prod: &prod
    directory: &directory dbfs:/mnt/centralds/offerallocation/headroom/test_run/v0.5/
    prod_input: &prod_input "dbfs:/mnt/centralds/offerallocation/headroom/prod_run/prod_input/"
    upcoming_campaign: &upcoming_campaign "202204"
    verions:
      data: &vdata v0.0.7
      model: &vmodel v0.0.7
      prediction: &vprediction v0.0.6
    steps: [segmentation, build_dataset, fit_rec, predict]
    # offline_eval
    date_format: &date_format '%Y%m%d'
    dates:
      start_date: &start_date 20220105
      end_date: &end_date 20220331
      etl_date: &etl_date 20220331
    columns:
      user_id: &user_id "cust_id"
      item_id: &item_id "l2_id"
      l1_ids: &l1_ids ["FD"]
      # ["GM"]
      lx: &lx "l2"
      feature_col: &feature_col "mean_spend_timespan"
      # "mean_spend_timespan"
      # "average_basket_value"
      #"total_spend" #"number_of_transactions"
      # Segmentation columns
      seg_num_cols: &seg_num_cols ["age_to_use", "FD_spend", "GM_spend", "FD_items",  "GM_items", "FD_baskets", "GM_baskets" ]
      seg_cat_cols: &seg_cat_cols ["experian_hh_composition"]
      # "experian_hh_composition", "experian_mosaic_uk_type"
      # ""
    segmentation:
      # input
      etl_date: *etl_date
      lookback_days: 365
      l1_id: "FD"
      user_id: *user_id
      cust_path: [*prod_input, *upcoming_campaign, "customers"]
      num_cols: *seg_num_cols
      cat_cols: *seg_cat_cols
      frac_lim: 0.1
      fail_limit: 3
      k_search_min: 2
      k_search_max: 8
      pca_k: 3
      data_lower_lim: 200000
      verbose: True
      # output
      write_mode: overwrite # errorifexists # overwrite
      partitionByList: &partitionByList ["experian_hh_composition", "segmentation"]
      seg_data_path: &seg_data_path [*directory, "data", *upcoming_campaign, *vdata, "segmentations"]
      custs_data_seg_path: &custs_data_seg_path [*directory, "data", *upcoming_campaign, *vdata, "cust_segment"]
    use_segments:
      all: True
      # seg_list e.g. [{'experian_hh_composition': 'Cat_U', 'segmentation': 1}, ...]
      seg_list: {}
      custs_data_seg_path: *custs_data_seg_path
      partitionByList: *partitionByList
    build_dataset:
      # input
      cust_input_path: *custs_data_seg_path
      start_date: *start_date
      end_date: *end_date
      user_id: *user_id
      l1_ids: *l1_ids
      lx: *lx
      lx_ids: &lx_ids ["EX01", "EX02", "EX03", "EX04", "EX05", "EX07", "EX09"]
      # "EX08" - Non Trading
      # ["01", "02", "03", "04", "05", "07"]
      date_format: *date_format
      window_days: 30
      # output
      partitionByList: *partitionByList
      write_mode: overwrite # errorifexists # overwrite
      etl_data_path: &etl_data_path [*directory, "data", *upcoming_campaign, *vdata, "purch_hist"]
    fit_rec:
      # input
      etl_data_path: *etl_data_path
      user_id: *user_id
      item_id: *item_id
      feature_col: *feature_col
      max_train_size: 100000
      n_threads: 5
      lognorm: &lognorm True
      method: &method "SVD"
      line_format: "user item rating"
      rating_scale: (-10, 0)
      min_lim: 0
      max_lim: 500
      cat_cols: *seg_cat_cols
      partitionByList: *partitionByList
      params: None
#      {'n_factors': 100, 'n_epochs': 20, 'biased': True, 'init_mean': 0, 'init_std_dev': 0.1, 'lr_bu': 0.005,
#       'lr_bi': 0.005, 'lr_pu': 0.005, 'lr_qi': 0.005, 'reg_bu': 0.02, 'reg_bi': 0.02, 'reg_pu': 0.02,'reg_qi': 0.02}
      param_grid: {'n_factors':[50,100,150],'n_epochs':[20,30],  'lr_all':[0.005,0.01],'reg_all':[0.02,0.1]}
      # output
      write_mode: overwrite # errorifexists # overwrite
      data_processor_path: &data_processor_path [*directory, "model", *upcoming_campaign, *vmodel, "data_processor"]
      param_path: &param_path [*directory, "params", *upcoming_campaign, *vmodel, *method]
      rec_path: &rec_path [*directory, "model", *upcoming_campaign, *vmodel, *method]
    predict:
      # input
      pred_data_path: *etl_data_path
      data_processor_path: *data_processor_path
      rec_path: *rec_path
      feature_col: *feature_col
      pred_key: *lx
      pred_items: *lx_ids
      cat_cols: *seg_cat_cols
      partitionByList: *partitionByList
      # output
      write_mode: overwrite # errorifexists # overwrite
      pred_path: &pred_path [*directory, "prediction", *upcoming_campaign, *vprediction, "predictions"]
    offline_eval:
      # input
      eval_data_path: *etl_data_path
      data_processor_path: *data_processor_path
      method: *method
      # ["svd", "svdpp", "nmf", "knn", "knn_zscore", "knn_mean"]
      methods: ["svd", "svdpp", "nmf"]
      sample: None
      dev_size: 0.1
      test_size: 0.1
      split_col: *user_id
      random_state: 42
      user_key: *user_id
      pred_key: *lx
      pred_items: *lx_ids
      kfold: True
      n_splits: 5
      shuffle: True



  dev: *prod

